on: [push]
name: Benchmark

jobs:
  build_and_test:
    name: Advent of Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install dependencies
        run: |
          cargo install cargo-criterion --locked
          cargo install criterion-table --locked

      - name: Start benchmarks
        run: cargo criterion --message-format=json | criterion-table > BENCHMARKS.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update benchmarks
